version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/nginx/log:/var/log/nginx
      - /home/nginx/html:/usr/share/nginx/html
      - /home/nginx/ssl:/etc/nginx/ssl
      - /home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/conf/certs:/etc/nginx/conf/certs
      - /home/nginx/conf/conf.d:/etc/nginx/conf.d
    networks:
      - douban-net
    depends_on:
      - douban-server

  postgres:
    image: postgres:latest
    container_name: pg
    networks:
      - douban-net
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: douban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cptbtptp1
    restart: unless-stopped

  douban-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: douban-server
    ports:
      - "8000:8000"
    networks:
      - douban-net
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: douban
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Cptbtptp1
    restart: unless-stopped

networks:
  douban-net:
    external: true

volumes:
  postgres-data:
